package com.honeywell.wholesale.framework.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "customer".
*/
public class CustomerDao extends AbstractDao<Customer, Long> {

    public static final String TABLENAME = "customer";

    /**
     * Properties of entity Customer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CustomerId = new Property(1, String.class, "customerId", false, "customer_id");
        public final static Property ContactName = new Property(2, String.class, "contactName", false, "contact_name");
        public final static Property ShopId = new Property(3, String.class, "shopId", false, "shop_id");
        public final static Property ContactPhone = new Property(4, String.class, "contactPhone", false, "contact_phone");
        public final static Property CustomerName = new Property(5, String.class, "customerName", false, "customer_name");
        public final static Property Meno = new Property(6, String.class, "meno", false, "memo");
        public final static Property CustomerAddress = new Property(7, String.class, "customerAddress", false, "address");
        public final static Property InvoiceTitle = new Property(8, String.class, "invoiceTitle", false, "invoice_title");
        public final static Property CusGroup = new Property(9, String.class, "cusGroup", false, "cus_group");
        public final static Property Pinyin = new Property(10, String.class, "pinyin", false, "pinyin");
        public final static Property Initias = new Property(11, String.class, "initias", false, "initials");
    }


    public CustomerDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"customer\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"customer_id\" TEXT," + // 1: customerId
                "\"contact_name\" TEXT," + // 2: contactName
                "\"shop_id\" TEXT," + // 3: shopId
                "\"contact_phone\" TEXT," + // 4: contactPhone
                "\"customer_name\" TEXT," + // 5: customerName
                "\"memo\" TEXT," + // 6: meno
                "\"address\" TEXT," + // 7: customerAddress
                "\"invoice_title\" TEXT," + // 8: invoiceTitle
                "\"cus_group\" TEXT," + // 9: cusGroup
                "\"pinyin\" TEXT," + // 10: pinyin
                "\"initials\" TEXT);"); // 11: initias
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"customer\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Customer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String customerId = entity.getCustomerId();
        if (customerId != null) {
            stmt.bindString(2, customerId);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(3, contactName);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(4, shopId);
        }
 
        String contactPhone = entity.getContactPhone();
        if (contactPhone != null) {
            stmt.bindString(5, contactPhone);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(6, customerName);
        }
 
        String meno = entity.getMeno();
        if (meno != null) {
            stmt.bindString(7, meno);
        }
 
        String customerAddress = entity.getCustomerAddress();
        if (customerAddress != null) {
            stmt.bindString(8, customerAddress);
        }
 
        String invoiceTitle = entity.getInvoiceTitle();
        if (invoiceTitle != null) {
            stmt.bindString(9, invoiceTitle);
        }
 
        String cusGroup = entity.getCusGroup();
        if (cusGroup != null) {
            stmt.bindString(10, cusGroup);
        }
 
        String pinyin = entity.getPinyin();
        if (pinyin != null) {
            stmt.bindString(11, pinyin);
        }
 
        String initias = entity.getInitias();
        if (initias != null) {
            stmt.bindString(12, initias);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Customer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String customerId = entity.getCustomerId();
        if (customerId != null) {
            stmt.bindString(2, customerId);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(3, contactName);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(4, shopId);
        }
 
        String contactPhone = entity.getContactPhone();
        if (contactPhone != null) {
            stmt.bindString(5, contactPhone);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(6, customerName);
        }
 
        String meno = entity.getMeno();
        if (meno != null) {
            stmt.bindString(7, meno);
        }
 
        String customerAddress = entity.getCustomerAddress();
        if (customerAddress != null) {
            stmt.bindString(8, customerAddress);
        }
 
        String invoiceTitle = entity.getInvoiceTitle();
        if (invoiceTitle != null) {
            stmt.bindString(9, invoiceTitle);
        }
 
        String cusGroup = entity.getCusGroup();
        if (cusGroup != null) {
            stmt.bindString(10, cusGroup);
        }
 
        String pinyin = entity.getPinyin();
        if (pinyin != null) {
            stmt.bindString(11, pinyin);
        }
 
        String initias = entity.getInitias();
        if (initias != null) {
            stmt.bindString(12, initias);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Customer readEntity(Cursor cursor, int offset) {
        Customer entity = new Customer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // customerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // contactName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // shopId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // contactPhone
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // customerName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // meno
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // customerAddress
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // invoiceTitle
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // cusGroup
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // pinyin
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // initias
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Customer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustomerId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContactName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShopId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContactPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCustomerName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMeno(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCustomerAddress(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setInvoiceTitle(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCusGroup(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPinyin(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setInitias(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Customer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Customer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Customer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
