package com.honeywell.wholesale.framework.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.honeywell.wholesale.framework.db.Account;
import com.honeywell.wholesale.framework.db.Cart;
import com.honeywell.wholesale.framework.db.Category;
import com.honeywell.wholesale.framework.db.Customer;
import com.honeywell.wholesale.framework.db.Employee;
import com.honeywell.wholesale.framework.db.Incremental;
import com.honeywell.wholesale.framework.db.Shop;

import com.honeywell.wholesale.framework.db.AccountDao;
import com.honeywell.wholesale.framework.db.CartDao;
import com.honeywell.wholesale.framework.db.CategoryDao;
import com.honeywell.wholesale.framework.db.CustomerDao;
import com.honeywell.wholesale.framework.db.EmployeeDao;
import com.honeywell.wholesale.framework.db.IncrementalDao;
import com.honeywell.wholesale.framework.db.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig cartDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig employeeDaoConfig;
    private final DaoConfig incrementalDaoConfig;
    private final DaoConfig shopDaoConfig;

    private final AccountDao accountDao;
    private final CartDao cartDao;
    private final CategoryDao categoryDao;
    private final CustomerDao customerDao;
    private final EmployeeDao employeeDao;
    private final IncrementalDao incrementalDao;
    private final ShopDao shopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        employeeDaoConfig = daoConfigMap.get(EmployeeDao.class).clone();
        employeeDaoConfig.initIdentityScope(type);

        incrementalDaoConfig = daoConfigMap.get(IncrementalDao.class).clone();
        incrementalDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        cartDao = new CartDao(cartDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        employeeDao = new EmployeeDao(employeeDaoConfig, this);
        incrementalDao = new IncrementalDao(incrementalDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Cart.class, cartDao);
        registerDao(Category.class, categoryDao);
        registerDao(Customer.class, customerDao);
        registerDao(Employee.class, employeeDao);
        registerDao(Incremental.class, incrementalDao);
        registerDao(Shop.class, shopDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        cartDaoConfig.clearIdentityScope();
        categoryDaoConfig.clearIdentityScope();
        customerDaoConfig.clearIdentityScope();
        employeeDaoConfig.clearIdentityScope();
        incrementalDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public CartDao getCartDao() {
        return cartDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public EmployeeDao getEmployeeDao() {
        return employeeDao;
    }

    public IncrementalDao getIncrementalDao() {
        return incrementalDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

}
