package com.honeywell.wholesale.framework.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "incremental".
*/
public class IncrementalDao extends AbstractDao<Incremental, Long> {

    public static final String TABLENAME = "incremental";

    /**
     * Properties of entity Incremental.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IncrementalKey = new Property(1, String.class, "incrementalKey", false, "incremental_key");
        public final static Property Time = new Property(2, String.class, "time", false, "time");
        public final static Property ShopId = new Property(3, String.class, "shopId", false, "shopId");
    }


    public IncrementalDao(DaoConfig config) {
        super(config);
    }
    
    public IncrementalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"incremental\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"incremental_key\" TEXT," + // 1: incrementalKey
                "\"time\" TEXT," + // 2: time
                "\"shopId\" TEXT);"); // 3: shopId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"incremental\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Incremental entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String incrementalKey = entity.getIncrementalKey();
        if (incrementalKey != null) {
            stmt.bindString(2, incrementalKey);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(4, shopId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Incremental entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String incrementalKey = entity.getIncrementalKey();
        if (incrementalKey != null) {
            stmt.bindString(2, incrementalKey);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(4, shopId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Incremental readEntity(Cursor cursor, int offset) {
        Incremental entity = new Incremental( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // incrementalKey
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // shopId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Incremental entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIncrementalKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShopId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Incremental entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Incremental entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Incremental entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
