package com.honeywell.wholesale.framework.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "shop".
*/
public class ShopDao extends AbstractDao<Shop, Long> {

    public static final String TABLENAME = "shop";

    /**
     * Properties of entity Shop.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShopId = new Property(1, String.class, "shopId", false, "shop_id");
        public final static Property AccountId = new Property(2, String.class, "accountId", false, "account_id");
        public final static Property ShopName = new Property(3, String.class, "shopName", false, "shop_name");
    }


    public ShopDao(DaoConfig config) {
        super(config);
    }
    
    public ShopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"shop\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"shop_id\" TEXT," + // 1: shopId
                "\"account_id\" TEXT," + // 2: accountId
                "\"shop_name\" TEXT);"); // 3: shopName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"shop\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Shop entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(2, shopId);
        }
 
        String accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindString(3, accountId);
        }
 
        String shopName = entity.getShopName();
        if (shopName != null) {
            stmt.bindString(4, shopName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Shop entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(2, shopId);
        }
 
        String accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindString(3, accountId);
        }
 
        String shopName = entity.getShopName();
        if (shopName != null) {
            stmt.bindString(4, shopName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Shop readEntity(Cursor cursor, int offset) {
        Shop entity = new Shop( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shopId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // accountId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // shopName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Shop entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShopId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAccountId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShopName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Shop entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Shop entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Shop entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
